# Generated by Django 5.2.5 on 2025-09-04 00:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_alter_song_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
