# Generated by Django 5.2.5 on 2025-09-04 02:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_alter_song_audio_file_alter_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
